CIRCUIT_PROFILES: dict[str, dict] = {
    "silverstone": {
        "pit_loss_seconds": 20.5,
        "overtaking_difficulty": 0.4,
        "tyre_degradation_index": 0.8,
        "safety_car_rate": 0.45,
        "circuit_type": "high_df",
        "is_street": False,
        "high_speed_pct": 0.45,
        "braking_intensity": 0.4,
    },
    "monaco": {
        "pit_loss_seconds": 19.0,
        "overtaking_difficulty": 0.95,
        "tyre_degradation_index": 0.2,
        "safety_car_rate": 0.80,
        "circuit_type": "street",
        "is_street": True,
        "high_speed_pct": 0.10,
        "braking_intensity": 0.7,
    },
    "monza": {
        "pit_loss_seconds": 24.0,
        "overtaking_difficulty": 0.35,
        "tyre_degradation_index": 0.4,
        "safety_car_rate": 0.40,
        "circuit_type": "power",
        "is_street": False,
        "high_speed_pct": 0.65,
        "braking_intensity": 0.6,
    },
    "spa": {
        "pit_loss_seconds": 22.0,
        "overtaking_difficulty": 0.30,
        "tyre_degradation_index": 0.7,
        "safety_car_rate": 0.50,
        "circuit_type": "power",
        "is_street": False,
        "high_speed_pct": 0.55,
        "braking_intensity": 0.4,
    },
    "bahrain": {
        "pit_loss_seconds": 22.5,
        "overtaking_difficulty": 0.35,
        "tyre_degradation_index": 0.9,
        "safety_car_rate": 0.55,
        "circuit_type": "tyre_limited",
        "is_street": False,
        "high_speed_pct": 0.30,
        "braking_intensity": 0.7,
    },
    "singapore": {
        "pit_loss_seconds": 28.0,
        "overtaking_difficulty": 0.85,
        "tyre_degradation_index": 0.6,
        "safety_car_rate": 0.95,
        "circuit_type": "street",
        "is_street": True,
        "high_speed_pct": 0.15,
        "braking_intensity": 0.8,
    },
    "default": {
        "pit_loss_seconds": 22.0,
        "overtaking_difficulty": 0.50,
        "tyre_degradation_index": 0.5,
        "safety_car_rate": 0.50,
        "circuit_type": "balanced",
        "is_street": False,
        "high_speed_pct": 0.30,
        "braking_intensity": 0.5,
    }
}

def get_circuit_profile(circuit_id: str) -> dict:
    return CIRCUIT_PROFILES.get(circuit_id, CIRCUIT_PROFILES["default"])
